# Generated by Django 4.2.2 on 2023-06-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('carry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='driver.driver'),
        ),
    ]
