# Generated by Django 4.2.2 on 2023-06-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_is_free'),
        ('carry', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='driver.driver'),
        ),
    ]
