# Generated by Django 4.2.2 on 2023-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='token',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
