# Generated by Django 4.2.2 on 2023-06-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
