# Generated by Django 4.2.2 on 2023-06-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.manager')),
            ],
        ),
    ]
