# Generated by Django 4.1.4 on 2023-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dest_long',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='src_lat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='src_long',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
